export const GET_FOOD_LIST = 'GET_FOOD_LIST';
export const GET_SELECTED_ITEM = 'GET_SELECTED_ITEM';
export const SET_SELECTED_ITEM = 'SET_SELECTED_ITEM';

export const ADD_STOCK = 'ADD_STOCK'
export const DELETE_TEMP_STOCK = 'DELETE_TEMP_STOCK'
export const COMMIT_STOCK_ADDS = 'COMMIT_STOCK_ADDS'
export const CLEAR_TEMP_STOCK = 'CLEAR_TEMP_STOCK'

export const CLEAR_TEMP_DEMAND = 'CLEAR_TEMP_DEMAND'
export const COMMIT_STOCK_DEMAND ='COMMIT_STOCK_DEMAND'
export const DELETE_TEMP_DEMAND ='DELETE_TEMP_DEMAND'
export const ADD_DEMAND='ADD_DEMAND'

export const CLEAR_TEMP_DRAWING = 'CLEAR_TEMP_DRAWING'
export const COMMIT_STOCK_DRAWING = 'COMMIT_STOCK_DRAWING'
export const DELETE_TEMP_DRAWING = 'DELETE_TEMP_DRAWING'
export const ADD_DRAWING = 'ADD_DRAWING'


export const ADDTO_PURCHASE_ITEM = 'ADDTO_PURCHASE_ITEM'

//sending request to server
export const REQUEST_FOOD_ITEMS = 'REQUEST_FOOD_ITEMS' 
export const RECEIVE_FOOD_ITEMS = 'RECEIVE_FOOD_ITEMS'
export const ERROR_REQUEST = 'ERROR_REQUEST'

export const REQUEST_SUPPLIERS = 'REQUEST_SUPPLIERS' 
export const RECEIVE_SUPPLIERS = 'RECEIVE_SUPPLIERS'

export const RECEIVE_PURCHASE_ORDER = 'RECEIVE_PURCHASE_ORDER'
export const REQUEST_PURCHASE_ORDER = 'REQUEST_PURCHASE_ORDER'
