export const ADDTO_PURCHASE_ITEM = 'ADDTO_PURCHASE_ITEM'

export const ADD_DRAWING = 'ADD_DRAWING'
export const COMMIT_DRAWING = 'COMMIT_DRAWING'
export const DEL_DRAWING = 'DEL_DRAWING'
export const CLEAR_DRAWINGS = 'CLEAR_DRAWINGS'


export const ADD_DEMAND = 'ADD_DEMAND'
export const COMMIT_DEMAND ='COMMIT_DEMAND'
export const DEL_DEMAND = 'DEL_DEMAND'
export const CLEAR_DEMAND = 'CLEAR_DEMAND'
//sending request to server
export const REQUEST_FOOD_ITEMS = 'REQUEST_FOOD_ITEMS' 
export const RECEIVE_FOOD_ITEMS = 'RECEIVE_FOOD_ITEMS'
export const INVALIDATE_FOOD_ITEMS = 'INVALIDATE_FOOD_ITEMS'

export const ERROR_RESPONSE = 'ERROR_RESPONSE'
export const RECEIVE_SUCCESS_MESSAGE = 'RECEIVE_SUCCESS_MESSAGE'

export const REQUEST_SUPPLIERS = 'REQUEST_SUPPLIERS' 
export const RECEIVE_SUPPLIERS = 'RECEIVE_SUPPLIERS'
export const INVALIDATE_SUPPLIERS = 'INVALIDATE_SUPPLIERS'

export const RECEIVE_PURCHASE_ORDER = 'RECEIVE_PURCHASE_ORDER'
export const REQUEST_PURCHASE_ORDER = 'REQUEST_PURCHASE_ORDER'
export const INVALIDATE_PURCHASE_ORDER = 'INVALIDATE_PURCHASE_ORDER'
export const COMMIT_PURCHASE_ORDER = 'COMMIT_PURCHASE_ORDER'
